title: Bail Funds
description: >-
  A collection of community resources for protestors around the country.
baseurl: ""
url: "https://bailfunds.github.io"

timezone: US/Eastern

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

github:
  is_project_page: false

google_analytics: UA-168258236-1

markdown: kramdown